version: 2.1

jobs:
  build:
    macos:
      xcode: 15.0

    steps:
      - checkout
      - run: fastlane scan --project "MovieAPI/MovieAPI.xcodeproj" --scheme 'MovieAPI'
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output

workflows:
  tests:
    jobs:
      - build
