name: Testing

on:
  pull_request

jobs:
  test:
    name: Testing Swift Package and iOS App
    runs-on: macOS-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Xcode Setup
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1'

      - name: Build with proper path
        run: |
          xcodebuild build -resolvePackageDependencies -workspace MovieAPI/MovieAPI.xcworkspace -scheme MovieAPI clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No

      - name: Run tests with proper path and destination
        id: xcodebuild
        run: |
            xcodebuild build -resolvePackageDependencies -workspace MovieAPI/MovieAPI.xcworkspace -scheme MovieAPI clean build -sdk iphoneos CODE_SIGNING_ALLOWED=No


