name: iOS starter workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Xcode Test
      uses: devbotsxyz/xcode-test@v1
      with:
        project: 'MovieAPI.xsproj' # `project` and `workspace` cannot be used at the same time
        scheme: 'scheme'
        configuration: Debug
        destination: platform=iOS Simulator,OS=latest,name=iPhone 11
